site_name: MkMods
site_url: https://tempmailo.com/
site_description: Project documentation with Markdown.
site_author: Tempmailo

repo_url: "" #https://github.com/ReadTheDcs/MkMod
edit_uri: ""

theme:
    name: material
    custom_dir: 'mkdocs/themes/material/'
    highlightjs: true
    hljs_languages:
        - yaml
        - django


extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright: Copyright &copy; 2019 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
